import Vue from 'vue';
import pt from 'vuetify/es5/locale/pt';
import colors from 'vuetify/es5/util/colors';

import Vuetify, {
    VApp,
    VCard,
    VCardTitle,
    VCardText,
    VCarousel,
    VCarouselItem,
    VTextField,
    VCheckbox,
    VLabel,
    VSelect,
    VBtn,
    VMain,
    VSnackbar,
    VImg,
    VIcon,
    VSlider,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VStepper,
    VStepperItems,
    VStepperContent,
    VLazy,
    VOverlay,
    VNavigationDrawer,
    VAppBar,
    VAppBarNavIcon,
    VSpacer,
    VList,
    VListItem,
    VListItemIcon,
    VListItemContent,
    VListItemTitle,
    VSimpleTable,
    VMenu,
    VFooter,
    VBreadcrumbs,
    VRadioGroup,
    VRadio
} from 'vuetify/lib';

Vue.use(Vuetify, {
    components: {
        VApp,
        VCard,
        VCardTitle,
        VCardText,
        VCarousel,
        VCarouselItem,
        VTextField,
        VCheckbox,
        VLabel,
        VSelect,
        VBtn,
        VMain,
        VSnackbar,
        VImg,
        VIcon,
        VSlider,
        VExpansionPanels,
        VExpansionPanel,
        VExpansionPanelHeader,
        VExpansionPanelContent,
        VStepper,
        VStepperItems,
        VStepperContent,
        VLazy,
        VOverlay,
        VNavigationDrawer,
        VAppBar,
        VAppBarNavIcon,
        VSpacer,
        VList,
        VListItem,
        VListItemIcon,
        VListItemContent,
        VListItemTitle,
        VSimpleTable,
        VMenu,
        VFooter,
        VBreadcrumbs,
        VRadioGroup,
        VRadio,
    },
});

export default new Vuetify({
  icons: {
    iconfont: 'mdiSvg', // 'mdi' || 'mdiSvg' || 'md' || 'fa' || 'fa4' || 'faSvg'
  },
    lang: {
        locales: { pt },
        current: 'pt',
    },
    defaultAssets: false,
    theme: {
        dark: false,
        themes: {
            light: {
                primary: '#1c5ca2',
                secondary: '#183f6a',
                accent: '#f2f2f2',
                white: '#FFFFFF',
                'black': '#484848',
                info: colors.teal.lighten1,
                warning: colors.amber.base,
                error: colors.deepOrange.accent4,
                success: colors.green.accent3,
            },
        },
    },
});
